In [1]:
import boto3
import pickle

To help the team steps I followed

1. How to setup AWS account?

Just google search that and follow the below step. I got 12 free trail
https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/

Once I sign then i use code PCU1DK92QNSSSU to get 500 class credit in credential which I got from professor and each team member has 
500 credit

2. Steps to get the code running

I follow the step https://docs.aws.amazon.com/sagemaker/latest/dg/gs-console.html

Step 1: Create an Amazon S3 Bucket
Step 2: Create an Amazon SageMaker Notebook Instance
I need large instance for that i reach out to AWS support and cc the team in the email also.

Step 3: Create a Jupyter Notebook

Also reach out to AWS support for any issues.

I did lots of google search and listen to youtube videos to resolve any issue i encounter 
since this is the first time I am using AWS.

For Data exploration as I mention in the meeting for 2nd feb for Tuesday, I am going to replicate 

1. Summary of BGG Dataset features.(Already done)
2. Summary of features in User ratings.
3. Statistics of datasets.

from paper https://www.mdpi.com/2073-8994/12/2/210/htm

Later I will perform additional data statistics based on tueday feedback from prof.



!pwd

In [13]:
import h5py

In [32]:
import tables

In [38]:
import numpy as np

In [2]:
# download preprocessed data from S3
s3 = boto3.client('s3')

###  AWS bucket with original data

In [3]:
bucket = 'w210-capstone-2021'
s3.download_file(bucket, 'np_games_info.zip', './np_games_info.zip')

Unzip the file in the terminal

In [7]:
with open('np_games_info.pkl', 'rb') as f:
    data = pickle.load(f)

The database comprises board games with their metadata such as title, ratings, production year, publisher, types, categories, and other details. 


The data is a numpy array, Summary of BGG dataset features

1. Game ID
2. Name of the game
3. Year released
4. Number of players, playing time, age, rating
5. Designer, Artist, Publisher
6. Type of game
7. Labels
8. Dictionary of ratings by users

In [51]:
data[0][0:7]

array([1, 'Die Macher', 1986, list(['3–5', '240', '14+', '4.34']),
       list([['Karl-Heinz Schmiel'], ['Marcus Gschwendtner', 'Harald Lieske'], ['Hans im Glück', 'Moskito Spiele']]),
       list(['Strategy']), list(['Economic', 'Negotiation', 'Political'])],
      dtype=object)

In [ ]:
data[0][-1]

In [ ]:
### Number of games
### large-scale dataset of user-game interactions from BGG for research in games. It contains 108,536 board games and 511,960 users 

In [36]:
len(data)

108571

In [41]:
ratings_per_game = np.array([len(x[-1]) for x in data])

### Unique names

In [34]:
games = set(x[1] for x in data)

In [35]:
len(games)

104344

### Distribution of ratings per game

In [42]:
ratings_per_game.mean()

438.64040121211

In [49]:
np.histogram(ratings_per_game, bins = [0,10,100,1000,10000,100000,1000000])

(array([39296, 39480, 22154,  6835,   796,    10]),
 array([      0,      10,     100,    1000,   10000,  100000, 1000000]))

### Unique users

In [48]:
# slow, need to re-run
users = set()
for x in data:
    users = users | set(list(x[-1].keys()))

KeyboardInterrupt: 

In [ ]:
len(users)